name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Python Tests
        if: hashFiles('solutions/solution.py', 'tests/test_python.py') != ''
        run: |
          if [ -f "tests/test_python.py" ]; then
            pytest tests/test_python.py
          else
            echo "No Python test file found. Skipping."
          fi

      - name: Compile and Run C++ Tests
        if: hashFiles('solutions/*.cpp', 'tests/test_cpp.cpp') != ''
        run: |
          if [ -f "tests/test_cpp.cpp" ]; then
            g++ -o cpp_test tests/test_cpp.cpp solutions/*.cpp && ./cpp_test
          else
            echo "No C++ test file found. Skipping."
          fi

      - name: Compile and Run C Tests
        if: hashFiles('solutions/*.c', 'tests/test_c.c') != ''
        run: |
          if [ -f "tests/test_c.c" ]; then
            gcc -o c_test tests/test_c.c solutions/*.c && ./c_test
          else
            echo "No C test file found. Skipping."
          fi

      - name: Compile and Run Java Tests
        if: hashFiles('solutions/Main.java', 'tests/MainTest.java') != ''
        run: |
          if [ -f "tests/MainTest.java" ]; then
            javac -d . solutions/Main.java tests/MainTest.java
            java tests.MainTest
          else
            echo "No Java test file found. Skipping."
          fi
