name: Run Language-Specific Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      run_python: ${{ steps.filter.outputs.python_changed }}
      run_cpp: ${{ steps.filter.outputs.cpp_changed }}
      run_c: ${{ steps.filter.outputs.c_changed }}
      run_java: ${{ steps.filter.outputs.java_changed }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Modified Files
        id: filter
        run: |
          git fetch origin main --depth=1 || true

          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            CHANGED_FILES=$(git ls-files)  # First commit case
          fi

          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -qE 'solutions/solution.py|tests/test_python.py'; then
            echo "python_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/.*\.cpp|tests/test_cpp.cpp'; then
            echo "cpp_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/.*\.c|tests/test_c.c'; then
            echo "c_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/Main.java|tests/MainTest.java'; then
            echo "java_changed=true" >> $GITHUB_ENV
          fi

  test-python:
    needs: detect-changes
    if: env.python_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Python Tests
        run: |
          if [ -f "tests/test_python.py" ]; then
            pytest tests/test_python.py
          else
            echo "No Python test file found. Skipping."
          fi

  test-cpp:
    needs: detect-changes
    if: env.cpp_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run C++ Tests
        run: |
          if [ -f "tests/test_cpp.cpp" ]; then
            g++ -o cpp_test tests/test_cpp.cpp solutions/*.cpp && ./cpp_test
          else
            echo "No C++ test file found. Skipping."
          fi

  test-c:
    needs: detect-changes
    if: env.c_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run C Tests
        run: |
          if [ -f "tests/test_c.c" ]; then
            gcc -o c_test tests/test_c.c solutions/*.c && ./c_test
          else
            echo "No C test file found. Skipping."
          fi

  test-java:
    needs: detect-changes
    if: env.java_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run Java Tests
        run: |
          if [ -f "tests/MainTest.java" ]; then
            javac -d . solutions/Main.java tests/MainTest.java
            java tests.MainTest
          else
            echo "No Java test file found. Skipping."
          fi
