name: Conditional Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      run_python: ${{ steps.filter.outputs.python_changed }}
      run_cpp: ${{ steps.filter.outputs.cpp_changed }}
      run_c: ${{ steps.filter.outputs.c_changed }}
      run_java: ${{ steps.filter.outputs.java_changed }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Modified Files
        id: filter
        run: |
          git fetch origin main --depth=1
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -qE 'solutions/solution.py|tests/test_python.py'; then
            echo "Python files changed"
            echo "python_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/.*\.cpp|tests/test_cpp.cpp'; then
            echo "C++ files changed"
            echo "cpp_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/.*\.c|tests/test_c.c'; then
            echo "C files changed"
            echo "c_changed=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -qE 'solutions/Main.java|tests/MainTest.java'; then
            echo "Java files changed"
            echo "java_changed=true" >> $GITHUB_ENV
          fi

  python-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_python == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Python Tests
        run: pytest tests/test_python.py

  cpp-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_cpp == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run C++ Tests
        run: g++ -o cpp_test tests/test_cpp.cpp solutions/*.cpp && ./cpp_test

  c-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_c == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run C Tests
        run: gcc -o c_test tests/test_c.c solutions/*.c && ./c_test

  java-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_java == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile and Run Java Tests
        run: |
          javac -d . solutions/Main.java tests/MainTest.java
          java tests.MainTest
